/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description 헬스 체크 엔드포인트
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 상세 헬스 체크 (프로세스 상태 포함)
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/compare-analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Compare Analyze Task
         * @description 비교 분석 요청 (multipart). Phase 6 — task 생성 + SSE.
         *
         *     multipart:
         *       source: 원본 이미지 파일 (Vision Compare 컨텍스트에선 IMAGE_A)
         *       result: 결과 이미지 파일 (Vision Compare 컨텍스트에선 IMAGE_B)
         *       meta: JSON {context?, editPrompt?, compareHint?, historyItemId?, visionModel?, ollamaModel?}
         *
         *     응답: { task_id, stream_url } — 클라이언트가 stream_url 로 SSE 구독.
         */
        post: operations["create_compare_analyze_task_api_studio_compare_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/compare-analyze/stream/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Analyze Stream */
        get: operations["compare_analyze_stream_api_studio_compare_analyze_stream__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Edit Task
         * @description 수정 요청 (multipart): image 파일 + meta JSON + 옵션 reference_image.
         */
        post: operations["create_edit_task_api_studio_edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/edit/stream/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Edit Stream */
        get: operations["edit_stream_api_studio_edit_stream__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Generate Task
         * @description 생성 요청 받으면 백그라운드 파이프라인 spawn, task_id 반환.
         */
        post: operations["create_generate_task_api_studio_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/generate/stream/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generate Stream */
        get: operations["generate_stream_api_studio_generate_stream__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List History
         * @description 히스토리 조회 (최신순, mode 필터, cursor pagination).
         */
        get: operations["list_history_api_studio_history_get"];
        put?: never;
        post?: never;
        /** Clear History */
        delete: operations["clear_history_api_studio_history_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/history/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History Stats
         * @description 히스토리 통계 — 갯수 + 디스크 사용량 + 모드별 분해 (2026-04-27).
         */
        get: operations["history_stats_api_studio_history_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/history/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_studio_history__item_id__get"];
        put?: never;
        post?: never;
        /** Delete History */
        delete: operations["delete_history_api_studio_history__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interrupt Current
         * @description 현재 실행 중인 ComfyUI job 인터럽트 (전역). ComfyUI 는 client_id 관계없이 즉시 중단.
         */
        post: operations["interrupt_current_api_studio_interrupt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description 모델 프리셋 노출 — 프론트 model-presets.ts 와 snake_case 그대로 매핑.
         */
        get: operations["list_models_api_studio_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/ollama/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ollama Models
         * @description 설치된 Ollama 모델 목록 (Settings drawer 드롭다운용).
         *
         *     Returns:
         *         [{name, size_gb, modified_at}, ...] — 이름순 정렬.
         */
        get: operations["list_ollama_models_api_studio_ollama_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/process/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Process Status
         * @description 실 process_manager + system_metrics 로부터 Ollama·ComfyUI 상태 + 통합 자원 메트릭 조회.
         *
         *     응답 구조 (2026-04-26 헤더 통합 SystemMetrics 도입):
         *       {
         *         "ollama":  {"running": bool},
         *         "comfyui": {"running": bool, "vram_used_gb": float?, "vram_total_gb": float?,
         *                     "gpu_percent": float?},
         *         "system":  {"cpu_percent": float?, "ram_used_gb": float?, "ram_total_gb": float?},
         *         "vram_breakdown": {
         *           "comfyui": {"vram_gb": float, "models": [str], "last_mode": str?},
         *           "ollama":  {"vram_gb": float, "models": [{"name", "size_vram_gb", "expires_in_sec"}]},
         *           "other_gb": float
         *         }
         *       }
         *     각 메트릭 필드는 측정 실패 시 누락 가능 (프론트에서 누락 = 미표시 처리).
         *     vram_breakdown 은 항상 포함 (실패 시 0/빈 리스트) — 프론트에서 80% 임계 넘을 때만 표시.
         */
        get: operations["process_status_api_studio_process_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/process/{name}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Action */
        post: operations["process_action_api_studio_process__name___action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/reference-pool/orphans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pool Orphans
         * @description history 에서 참조 안 된 임시 풀 ref 목록.
         */
        get: operations["get_pool_orphans_api_studio_reference_pool_orphans_get"];
        put?: never;
        post?: never;
        /**
         * Delete Pool Orphans
         * @description orphan 일괄 삭제. 영구 라이브러리는 손대지 않음.
         *
         *     Race 완화 (Codex I4): delete 직전에 history snapshot 다시 조회 (double-check).
         */
        delete: operations["delete_pool_orphans_api_studio_reference_pool_orphans_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/reference-pool/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pool Stats
         * @description 임시 풀 사용량 — count + total bytes.
         */
        get: operations["get_pool_stats_api_studio_reference_pool_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/reference-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description 저장된 reference templates — last_used_at 내림차순.
         */
        get: operations["list_templates_api_studio_reference_templates_get"];
        put?: never;
        /**
         * Create Template
         * @description 신규 template 저장 — 이미지 + 메타 + 자동 vision 분석.
         *
         *     meta = { name: str, role?: str, userIntent?: str, visionModel?: str }
         *
         *     실패 정책:
         *       - 이미지 invalid: 400 (저장 X)
         *       - PIL 재인코딩 실패: 400 (저장 X)
         *       - DB insert 실패: 저장된 파일 unlink + 500 (orphan 방지)
         *       - vision 분석 실패: graceful — visionDescription=None 으로 저장 계속
         */
        post: operations["create_template_api_studio_reference_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/reference-templates/promote/{history_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote From History
         * @description v9 사후 저장 — 임시 풀 ref 를 영구 라이브러리로 promote.
         *
         *     흐름:
         *       1. history.referenceRef 가 임시 풀 URL 인지 검증 (pool_path_from_url 활용)
         *       2. 임시 풀 파일 read → save_reference_image() (영구 저장 + PIL 재인코딩)
         *       3. analyze_reference() — 실패 시 visionFailed=True silent
         *       4. insert_reference_template — 실패 시 dst unlink rollback
         *       5. studio_history.reference_ref → 영구 URL 로 swap (canPromote 자동 false)
         *
         *     Plan: 2026-04-29-reference-library-v9.md (Phase A.5)
         */
        post: operations["promote_from_history_api_studio_reference_templates_promote__history_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/reference-templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Template
         * @description 삭제 — DB row + 이미지 파일 모두 정리.
         *
         *     Soft 정책: 옛 history 의 reference_ref URL 은 보존 (이미지만 깨짐 표시).
         */
        delete: operations["delete_template_api_studio_reference_templates__template_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/reference-templates/{template_id}/touch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Touch Template
         * @description last_used_at 갱신 — 사용자가 이 템플릿으로 수정 실행 시.
         */
        post: operations["touch_template_api_studio_reference_templates__template_id__touch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research */
        post: operations["research_api_studio_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/system/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Launcher Shutdown
         * @description start_v2 로 띄운 로컬 스튜디오 프로세스 종료.
         *
         *     브라우저에서 누르는 종료 버튼용이라 localhost 요청만 허용한다.
         *     실제 종료는 별도 PowerShell 프로세스가 단계별로 수행한다.
         */
        post: operations["launcher_shutdown_api_studio_system_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/upgrade-only": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upgrade Only
         * @description 프롬프트 업그레이드 전용 (ComfyUI 미호출).
         *
         *     showUpgradeStep 프리퍼런스 ON 일 때 프론트가 호출 → 모달에서 사용자 확인 →
         *     /generate 로 preUpgradedPrompt 와 함께 재요청.
         *
         *     spec 19 후속 (Codex 추가 fix): aspect/width/height 도 SYSTEM_GENERATE 에
         *     전달 → /generate 본 호출과 동일한 size context 보장.
         */
        post: operations["upgrade_only_api_studio_upgrade_only_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Video Task
         * @description 영상 생성 요청 (multipart: image 파일 + meta JSON).
         *
         *     meta = { prompt, adult?, ollamaModel?, visionModel? }
         */
        post: operations["create_video_task_api_studio_video_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/video/stream/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Video Stream */
        get: operations["video_stream_api_studio_video_stream__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/vision-analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Vision Analyze Task
         * @description 단일 이미지 비전 분석 요청 (multipart). Phase 6 — task 생성 + SSE.
         *
         *     meta JSON: {visionModel?, ollamaModel?}
         *     응답: { task_id, stream_url } — 클라이언트가 stream_url 로 SSE 구독.
         *
         *     HTTP 200 원칙은 done event payload 안에서 보장 (provider="fallback" 폴백).
         */
        post: operations["create_vision_analyze_task_api_studio_vision_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/vision-analyze/stream/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vision Analyze Stream */
        get: operations["vision_analyze_stream_api_studio_vision_analyze_stream__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_compare_analyze_task_api_studio_compare_analyze_post */
        Body_create_compare_analyze_task_api_studio_compare_analyze_post: {
            /** Meta */
            meta: string;
            /** Result */
            result: string;
            /** Source */
            source: string;
        };
        /** Body_create_edit_task_api_studio_edit_post */
        Body_create_edit_task_api_studio_edit_post: {
            /** Image */
            image: string;
            /** Meta */
            meta: string;
            /** Reference Image */
            reference_image?: string | null;
        };
        /** Body_create_template_api_studio_reference_templates_post */
        Body_create_template_api_studio_reference_templates_post: {
            /** Image */
            image: string;
            /** Meta */
            meta: string;
        };
        /** Body_create_video_task_api_studio_video_post */
        Body_create_video_task_api_studio_video_post: {
            /** Image */
            image: string;
            /** Meta */
            meta: string;
        };
        /** Body_create_vision_analyze_task_api_studio_vision_analyze_post */
        Body_create_vision_analyze_task_api_studio_vision_analyze_post: {
            /** Image */
            image: string;
            /**
             * Meta
             * @default {}
             */
            meta: string;
        };
        /** GenerateBody */
        GenerateBody: {
            /**
             * Aspect
             * @default 1:1
             */
            aspect: string;
            /**
             * Cfg
             * @default 4
             */
            cfg: number;
            /** Height */
            height?: number | null;
            /**
             * Lightning
             * @default false
             */
            lightning: boolean;
            /** Ollamamodel */
            ollamaModel?: string | null;
            /** Preresearchhints */
            preResearchHints?: string[] | null;
            /** Preupgradedprompt */
            preUpgradedPrompt?: string | null;
            /** Prompt */
            prompt: string;
            /**
             * Research
             * @default false
             */
            research: boolean;
            /**
             * Seed
             * @default 464857551335368
             */
            seed: number;
            /**
             * Steps
             * @default 50
             */
            steps: number;
            /** Styleid */
            styleId?: string | null;
            /** Visionmodel */
            visionModel?: string | null;
            /** Width */
            width?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProcessAction */
        ProcessAction: {
            /** Message */
            message?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ResearchBody */
        ResearchBody: {
            /**
             * Model
             * @default Qwen Image 2512
             */
            model: string;
            /** Prompt */
            prompt: string;
        };
        /** TaskCreated */
        TaskCreated: {
            /** Stream Url */
            stream_url: string;
            /** Task Id */
            task_id: string;
        };
        /**
         * UpgradeOnlyBody
         * @description gemma4 업그레이드 + 선택적 조사만 수행 · ComfyUI 디스패치 없음.
         *
         *     spec 19 후속 (Codex 추가 fix): aspect/width/height 도 받아서 SYSTEM_GENERATE
         *     의 [Output dimensions] 컨텍스트에 정확한 dim 주입.
         *     GenerateBody 와 동일 필드 (옵셔널 · 미전달 시 aspect preset 폴백).
         */
        UpgradeOnlyBody: {
            /**
             * Aspect
             * @default 1:1
             */
            aspect: string;
            /** Height */
            height?: number | null;
            /** Ollamamodel */
            ollamaModel?: string | null;
            /** Prompt */
            prompt: string;
            /**
             * Research
             * @default false
             */
            research: boolean;
            /** Width */
            width?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** _PromoteBody */
        _PromoteBody: {
            /** Name */
            name: string;
            /** Role */
            role?: string | null;
            /** Userintent */
            userIntent?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_compare_analyze_task_api_studio_compare_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_compare_analyze_task_api_studio_compare_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_analyze_stream_api_studio_compare_analyze_stream__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_edit_task_api_studio_edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_edit_task_api_studio_edit_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_stream_api_studio_edit_stream__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_generate_task_api_studio_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_stream_api_studio_generate_stream__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_api_studio_history_get: {
        parameters: {
            query?: {
                mode?: string | null;
                limit?: number;
                before?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_history_api_studio_history_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    history_stats_api_studio_history_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_history_api_studio_history__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_history_api_studio_history__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interrupt_current_api_studio_interrupt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_models_api_studio_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_ollama_models_api_studio_ollama_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    process_status_api_studio_process_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    process_action_api_studio_process__name___action__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessAction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pool_orphans_api_studio_reference_pool_orphans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    delete_pool_orphans_api_studio_reference_pool_orphans_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_pool_stats_api_studio_reference_pool_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_templates_api_studio_reference_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_template_api_studio_reference_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_template_api_studio_reference_templates_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_from_history_api_studio_reference_templates_promote__history_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                history_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_PromoteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_studio_reference_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    touch_template_api_studio_reference_templates__template_id__touch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_api_studio_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launcher_shutdown_api_studio_system_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessAction"];
                };
            };
        };
    };
    upgrade_only_api_studio_upgrade_only_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpgradeOnlyBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_video_task_api_studio_video_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_video_task_api_studio_video_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    video_stream_api_studio_video_stream__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vision_analyze_task_api_studio_vision_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_vision_analyze_task_api_studio_vision_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vision_analyze_stream_api_studio_vision_analyze_stream__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
